name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main  # hoặc branch chính của bạn

permissions:
  contents: write  # cần quyền để push gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Chọn version Node phù hợp

      # 3. Cài dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build project
      - name: Build
        run: npm run build

      # 5. Deploy folder 'dist' lên gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
